Added a work around for docker bug in 1.9.1. See https://github.com/docker/docker/issues/18180 for more information.

diff --git a/runIDV b/runIDV
--- a/runIDV
+++ b/runIDV
@@ -15,7 +15,7 @@
 # idv_memory section below and subsequently choose memory via the Preferences
 # menu.  Be sure to comment it out that after setting the memory via the
 # Preferences if you want the preference to take effect.
-# 
+#
 # SunOS Users: To run the IDV in 64 bit mode to take advantage of improved
 # memory capacity, you may have to supply -d64 JVM argument. You must do this
 # in two places. See below for instructions.
@@ -29,7 +29,7 @@ dirname=`dirname $0`
 java="java"
 
 jre="jre"
-    
+
 if test -f ${jre}/bin/java; then
 # We are in the installer directory
     java=${jre}/bin/${java}
@@ -48,31 +48,31 @@ else
     fi
 fi
 
-# SunOS users: To run in 64 bit more, add -d64 before -client.  
+# SunOS users: To run in 64 bit more, add -d64 before -client.
 
 # On some UNIX operating systems, the line below will not work. The root issue
 # is that /bin/sh is not completely standard across all UNIX operating
 # systems. If that is the case, try this line instead
 # prefs=`${java} -client -cp ${dirname}/idv.jar ucar.unidata.idv.IdvCommandLinePrefs $* 2>&1`
-prefs="$(${java} -client -cp ${dirname}/idv.jar ucar.unidata.idv.IdvCommandLinePrefs $* 2>&1 )"
+# prefs="$(${java} -client -cp ${dirname}/idv.jar ucar.unidata.idv.IdvCommandLinePrefs $* 2>&1 )"
 
 if [ $? -eq 1 ]; then
     echo "${error_msg}"
     exit 1
 fi
 
-eval "${prefs}"
+# eval "${prefs}"
 
 # Sanity check. If memory variable does not exist, we have problems
-if test -z ${idv_memory}; then
-    echo "${error_msg}"
-    exit 1
-fi
+#if test -z ${idv_memory}; then
+#    echo "${error_msg}"
+#    exit 1
+#fi
 
 # See important note about this above. To bootstrap the IDV memory, uncomment
 # this line and set to a value in megabytes.
 # idv_memory=512
 
 
-# Sun OS users: To run in 64 bit mode, add -d64 before -Xmx.  
-${java}   -Xmx${idv_memory}m  -XX:+DisableExplicitGC -Didv.enableStereo=false -jar ${dirname}/idv.jar $*
+# Sun OS users: To run in 64 bit mode, add -d64 before -Xmx.
+${java}   -Xmx${DOCK_IDV_MEMORY}m -XX:+DisableExplicitGC -Didv.enableStereo=false -jar ${dirname}/idv.jar $*
